# Generated by Django 3.0.5 on 2020-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compose_name', models.CharField(max_length=255)),
                ('compose', models.PositiveSmallIntegerField(choices=[(1, 'Первый состав'), (2, 'Второй состав')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news_text', models.TextField()),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['news_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(help_text='Имя игрока', max_length=255)),
                ('player_sur_name', models.CharField(help_text='Фамилия игрока', max_length=255)),
                ('player_age', models.SmallIntegerField(help_text='Возраст')),
                ('player_position', models.PositiveSmallIntegerField(help_text='Позиция')),
                ('player_GK', models.SmallIntegerField(help_text='Показатель голкипера')),
                ('player_ATK', models.SmallIntegerField(help_text='Показатель нападения')),
                ('player_MID', models.SmallIntegerField(help_text='Показатель полузащиты')),
                ('player_DEF', models.SmallIntegerField(help_text='Показатель защиты')),
                ('player_compose', models.ManyToManyField(help_text='Состав (I/II)', to='mainn.Compose')),
            ],
        ),
    ]
