# Generated by Django 3.0.5 on 2020-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0003_auto_20200429_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='news_likes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, help_text='Фото', null=True, upload_to=''),
        ),
    ]
