# Generated by Django 3.0.5 on 2020-04-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0004_auto_20200429_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_likes',
            field=models.IntegerField(default=0),
        ),
    ]
