# Generated by Django 3.0.5 on 2020-05-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0008_auto_20200501_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_compose',
        ),
        migrations.AddField(
            model_name='player',
            name='player_compose',
            field=models.ForeignKey(default=1, help_text='Состав (I/II)', on_delete=django.db.models.deletion.CASCADE, to='mainn.Compose'),
        ),
    ]
