# Generated by Django 3.0.5 on 2020-05-11 10:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0011_playerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Добавить изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_ATK',
            field=models.SmallIntegerField(help_text='Показатель нападения (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Нападение'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_DEF',
            field=models.SmallIntegerField(help_text='Показатель защиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_GK',
            field=models.SmallIntegerField(help_text='Показатель голкипера (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Вратарь'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_MID',
            field=models.SmallIntegerField(help_text='Показатель полузащиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Полузащита'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_age',
            field=models.SmallIntegerField(help_text='Возраст', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_compose',
            field=models.ForeignKey(default=1, help_text='Состав (I/II)', on_delete=django.db.models.deletion.CASCADE, to='mainn.Compose', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, help_text='Фото', null=True, upload_to='', verbose_name='Добавить фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(help_text='Имя игрока', max_length=255, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Вратарь'), (2, 'Защитник'), (3, 'Полузащитник'), (6, 'Полунападающий'), (4, 'Нападающий'), (5, 'На замене')], default=5, help_text='Позиция', verbose_name='Игровая позиция'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sur_name',
            field=models.CharField(help_text='Фамилия игрока', max_length=255, verbose_name='Фамилия игрока'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_age',
            field=models.SmallIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_contacts',
            field=models.TextField(help_text='Ном.Тел, Viber, WhatsApp, Skype', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_name2',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
