# Generated by Django 3.0.5 on 2020-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0013_auto_20200513_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(choices=[('Goalkeeper', 'Вратарь'), (2, 'Защитник'), (3, 'Полузащитник'), (6, 'Полунападающий'), (4, 'Нападающий'), (5, 'На замене')], default=5, help_text='Позиция', max_length=13, verbose_name='Игровая позиция'),
        ),
    ]
