# Generated by Django 3.0.5 on 2020-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0016_auto_20200513_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
