# Generated by Django 3.0.5 on 2020-06-02 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0017_player_player_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_ATK',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_DEF',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_GK',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_MID',
        ),
        migrations.AddField(
            model_name='player',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.SmallIntegerField(default=0, help_text='Показатель защиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Забито голов'),
        ),
        migrations.AddField(
            model_name='player',
            name='missed',
            field=models.SmallIntegerField(default=0, help_text='Показатель полузащиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Пропущено матчей'),
        ),
        migrations.AddField(
            model_name='player',
            name='red',
            field=models.SmallIntegerField(default=0, help_text='Показатель нападения (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Красные карточки'),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow',
            field=models.SmallIntegerField(default=0, help_text='Показатель голкипера (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Желтые карточки'),
        ),
    ]
