# Generated by Django 3.0.5 on 2020-06-03 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0019_auto_20200603_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.SmallIntegerField(default=0, help_text='Показатель защиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забито голов'),
        ),
        migrations.AlterField(
            model_name='player',
            name='missed',
            field=models.SmallIntegerField(default=0, help_text='Показатель полузащиты (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Пропущено матчей'),
        ),
        migrations.AlterField(
            model_name='player',
            name='red',
            field=models.SmallIntegerField(default=0, help_text='Показатель нападения (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Красные карточки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow',
            field=models.SmallIntegerField(default=0, help_text='Показатель голкипера (мин - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Желтые карточки'),
        ),
    ]
