# Generated by Django 4.2.2 on 2023-07-04 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0021_geeksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compose',
            name='compose',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Перший склад'), (2, 'Другий склад')], default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.SmallIntegerField(default=0, help_text='Показник забитих мячів (мін - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Забито голів'),
        ),
        migrations.AlterField(
            model_name='player',
            name='missed',
            field=models.SmallIntegerField(default=0, help_text='Показник захисту (мін - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Пропущено матчів'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_age',
            field=models.SmallIntegerField(default=0, help_text='Вік', verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_compose',
            field=models.ForeignKey(default=1, help_text='Склад (I/II)', on_delete=django.db.models.deletion.CASCADE, to='mainn.compose', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, help_text='Фото', null=True, upload_to='', verbose_name='Додати фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(help_text='Имя гравця ', max_length=255, verbose_name='Имя гравця'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_position',
            field=models.CharField(choices=[('Голкіпер', 'Голкіпер'), ('Захисник', 'Захисник'), ('Напівнападаючий', 'Полузахист'), ('Полузахист', 'Напівнападаючий'), ('Нападаючий', 'Нападаючий'), ('Заміна', 'Заміна')], default='Заміна', help_text='Позиція', max_length=15, verbose_name='Ігрова позиція'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sur_name',
            field=models.CharField(help_text='Прізвище гравця', max_length=255, verbose_name='Прізвище гравця'),
        ),
        migrations.AlterField(
            model_name='player',
            name='red',
            field=models.SmallIntegerField(default=0, help_text='Показник нападу (мін - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Червоні картки'),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow',
            field=models.SmallIntegerField(default=0, help_text='Показник голкіпера (мін - 1, макс - 99)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Жовті картки'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_age',
            field=models.SmallIntegerField(default=0, verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_contacts',
            field=models.TextField(help_text='Ном.Тел, Viber, WhatsApp, Skype', verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_name2',
            field=models.CharField(max_length=255, verbose_name='Прізвище'),
        ),
    ]
