# Generated by Django 4.2.2 on 2023-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainn', '0022_alter_compose_compose_alter_player_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Додати зображення'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(help_text='Імя гравця ', max_length=255, verbose_name='Імя гравця'),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='player_request_name',
            field=models.CharField(max_length=255, verbose_name='Імя'),
        ),
    ]
